/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "ui2bs_constants.h"

namespace internal {

const ui2bsConstants g_ui2bs_constants;

ui2bsConstants::ui2bsConstants() {
}

} // namespace

