/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ui2bs_CONSTANTS_H
#define ui2bs_CONSTANTS_H

#include "ui2bs_types.h"

namespace internal {

class ui2bsConstants {
 public:
  ui2bsConstants();

};

extern const ui2bsConstants g_ui2bs_constants;

} // namespace

#endif
