// Code generated by protoc-gen-go.
// source: event.proto
// DO NOT EDIT!

/*
Package jesgoo_protocol is a generated protocol buffer package.

It is generated from these files:
	event.proto

It has these top-level messages:
	Event
*/
package jesgoo_protocol

import proto "code.google.com/p/goprotobuf/proto"
import math "math"
import jesgoo_protocol1 "jesgoo_protocol1"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type Event_Head_CryptoType int32

const (
	Event_Head_JESGOO_BASE64 Event_Head_CryptoType = 0
)

var Event_Head_CryptoType_name = map[int32]string{
	0: "JESGOO_BASE64",
}
var Event_Head_CryptoType_value = map[string]int32{
	"JESGOO_BASE64": 0,
}

func (x Event_Head_CryptoType) Enum() *Event_Head_CryptoType {
	p := new(Event_Head_CryptoType)
	*p = x
	return p
}
func (x Event_Head_CryptoType) String() string {
	return proto.EnumName(Event_Head_CryptoType_name, int32(x))
}
func (x *Event_Head_CryptoType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Event_Head_CryptoType_value, data, "Event_Head_CryptoType")
	if err != nil {
		return err
	}
	*x = Event_Head_CryptoType(value)
	return nil
}

type Event_Body_EventType int32

const (
	Event_Body_CLICK      Event_Body_EventType = 0
	Event_Body_IMPRESSION Event_Body_EventType = 1
	Event_Body_ACTIVATION Event_Body_EventType = 2
)

var Event_Body_EventType_name = map[int32]string{
	0: "CLICK",
	1: "IMPRESSION",
	2: "ACTIVATION",
}
var Event_Body_EventType_value = map[string]int32{
	"CLICK":      0,
	"IMPRESSION": 1,
	"ACTIVATION": 2,
}

func (x Event_Body_EventType) Enum() *Event_Body_EventType {
	p := new(Event_Body_EventType)
	*p = x
	return p
}
func (x Event_Body_EventType) String() string {
	return proto.EnumName(Event_Body_EventType_name, int32(x))
}
func (x *Event_Body_EventType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Event_Body_EventType_value, data, "Event_Body_EventType")
	if err != nil {
		return err
	}
	*x = Event_Body_EventType(value)
	return nil
}

type Event struct {
	Head             *Event_Head `protobuf:"bytes,1,req,name=head" json:"head,omitempty"`
	Body             *Event_Body `protobuf:"bytes,2,req,name=body" json:"body,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}

func (m *Event) GetHead() *Event_Head {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *Event) GetBody() *Event_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

type Event_Head struct {
	CryptoType       *Event_Head_CryptoType `protobuf:"varint,1,req,name=crypto_type,enum=jesgoo.protocol.Event_Head_CryptoType" json:"crypto_type,omitempty"`
	CryptoParam      *uint32                `protobuf:"varint,2,req,name=crypto_param" json:"crypto_param,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *Event_Head) Reset()         { *m = Event_Head{} }
func (m *Event_Head) String() string { return proto.CompactTextString(m) }
func (*Event_Head) ProtoMessage()    {}

func (m *Event_Head) GetCryptoType() Event_Head_CryptoType {
	if m != nil && m.CryptoType != nil {
		return *m.CryptoType
	}
	return Event_Head_JESGOO_BASE64
}

func (m *Event_Head) GetCryptoParam() uint32 {
	if m != nil && m.CryptoParam != nil {
		return *m.CryptoParam
	}
	return 0
}

type Event_Body struct {
	Type             *Event_Body_EventType `protobuf:"varint,1,req,name=type,enum=jesgoo.protocol.Event_Body_EventType" json:"type,omitempty"`
	SearchId         *string               `protobuf:"bytes,2,req,name=search_id" json:"search_id,omitempty"`
	SearchTimestamp  *uint32               `protobuf:"varint,3,req,name=search_timestamp" json:"search_timestamp,omitempty"`
	SearchIp         *uint32               `protobuf:"varint,4,opt,name=search_ip" json:"search_ip,omitempty"`
	EventTimestamp   *uint32               `protobuf:"varint,5,opt,name=event_timestamp" json:"event_timestamp,omitempty"`
	EventIp          *uint32               `protobuf:"varint,6,opt,name=event_ip" json:"event_ip,omitempty"`
	Media            *Event_Body_Media     `protobuf:"bytes,7,opt,name=media" json:"media,omitempty"`
	Region           *Event_Body_Region    `protobuf:"bytes,8,opt,name=region" json:"region,omitempty"`
	Ad               *Event_Body_Ad        `protobuf:"bytes,9,opt,name=ad" json:"ad,omitempty"`
	Charge           *Event_Body_Charge    `protobuf:"bytes,10,opt,name=charge" json:"charge,omitempty"`
	Dsp              *jesgoo_protocol1.Dsp `protobuf:"varint,11,opt,name=dsp,enum=jesgoo.protocol.Dsp" json:"dsp,omitempty"`
	Action           *Event_Body_Action    `protobuf:"bytes,12,opt,name=action" json:"action,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *Event_Body) Reset()         { *m = Event_Body{} }
func (m *Event_Body) String() string { return proto.CompactTextString(m) }
func (*Event_Body) ProtoMessage()    {}

func (m *Event_Body) GetType() Event_Body_EventType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Event_Body_CLICK
}

func (m *Event_Body) GetSearchId() string {
	if m != nil && m.SearchId != nil {
		return *m.SearchId
	}
	return ""
}

func (m *Event_Body) GetSearchTimestamp() uint32 {
	if m != nil && m.SearchTimestamp != nil {
		return *m.SearchTimestamp
	}
	return 0
}

func (m *Event_Body) GetSearchIp() uint32 {
	if m != nil && m.SearchIp != nil {
		return *m.SearchIp
	}
	return 0
}

func (m *Event_Body) GetEventTimestamp() uint32 {
	if m != nil && m.EventTimestamp != nil {
		return *m.EventTimestamp
	}
	return 0
}

func (m *Event_Body) GetEventIp() uint32 {
	if m != nil && m.EventIp != nil {
		return *m.EventIp
	}
	return 0
}

func (m *Event_Body) GetMedia() *Event_Body_Media {
	if m != nil {
		return m.Media
	}
	return nil
}

func (m *Event_Body) GetRegion() *Event_Body_Region {
	if m != nil {
		return m.Region
	}
	return nil
}

func (m *Event_Body) GetAd() *Event_Body_Ad {
	if m != nil {
		return m.Ad
	}
	return nil
}

func (m *Event_Body) GetCharge() *Event_Body_Charge {
	if m != nil {
		return m.Charge
	}
	return nil
}

func (m *Event_Body) GetDsp() jesgoo_protocol1.Dsp {
	if m != nil && m.Dsp != nil {
		return *m.Dsp
	}
	return jesgoo_protocol1.Dsp_JESGOO_DSP
}

func (m *Event_Body) GetAction() *Event_Body_Action {
	if m != nil {
		return m.Action
	}
	return nil
}

type Event_Body_Region struct {
	Country          *uint32 `protobuf:"varint,1,req,name=country" json:"country,omitempty"`
	Province         *uint32 `protobuf:"varint,2,req,name=province" json:"province,omitempty"`
	City             *uint32 `protobuf:"varint,3,req,name=city" json:"city,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Event_Body_Region) Reset()         { *m = Event_Body_Region{} }
func (m *Event_Body_Region) String() string { return proto.CompactTextString(m) }
func (*Event_Body_Region) ProtoMessage()    {}

func (m *Event_Body_Region) GetCountry() uint32 {
	if m != nil && m.Country != nil {
		return *m.Country
	}
	return 0
}

func (m *Event_Body_Region) GetProvince() uint32 {
	if m != nil && m.Province != nil {
		return *m.Province
	}
	return 0
}

func (m *Event_Body_Region) GetCity() uint32 {
	if m != nil && m.City != nil {
		return *m.City
	}
	return 0
}

type Event_Body_Media struct {
	MediaId          *string `protobuf:"bytes,1,req,name=media_id" json:"media_id,omitempty"`
	ChannelId        *string `protobuf:"bytes,2,opt,name=channel_id" json:"channel_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Event_Body_Media) Reset()         { *m = Event_Body_Media{} }
func (m *Event_Body_Media) String() string { return proto.CompactTextString(m) }
func (*Event_Body_Media) ProtoMessage()    {}

func (m *Event_Body_Media) GetMediaId() string {
	if m != nil && m.MediaId != nil {
		return *m.MediaId
	}
	return ""
}

func (m *Event_Body_Media) GetChannelId() string {
	if m != nil && m.ChannelId != nil {
		return *m.ChannelId
	}
	return ""
}

type Event_Body_Ad struct {
	UserId           *uint32 `protobuf:"varint,1,opt,name=user_id" json:"user_id,omitempty"`
	PlanId           *uint32 `protobuf:"varint,2,opt,name=plan_id" json:"plan_id,omitempty"`
	GroupId          *uint32 `protobuf:"varint,3,opt,name=group_id" json:"group_id,omitempty"`
	ProductId        *uint32 `protobuf:"varint,4,opt,name=product_id" json:"product_id,omitempty"`
	UnitId           *uint32 `protobuf:"varint,5,opt,name=unit_id" json:"unit_id,omitempty"`
	TemplateId       *uint32 `protobuf:"varint,6,opt,name=template_id" json:"template_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Event_Body_Ad) Reset()         { *m = Event_Body_Ad{} }
func (m *Event_Body_Ad) String() string { return proto.CompactTextString(m) }
func (*Event_Body_Ad) ProtoMessage()    {}

func (m *Event_Body_Ad) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *Event_Body_Ad) GetPlanId() uint32 {
	if m != nil && m.PlanId != nil {
		return *m.PlanId
	}
	return 0
}

func (m *Event_Body_Ad) GetGroupId() uint32 {
	if m != nil && m.GroupId != nil {
		return *m.GroupId
	}
	return 0
}

func (m *Event_Body_Ad) GetProductId() uint32 {
	if m != nil && m.ProductId != nil {
		return *m.ProductId
	}
	return 0
}

func (m *Event_Body_Ad) GetUnitId() uint32 {
	if m != nil && m.UnitId != nil {
		return *m.UnitId
	}
	return 0
}

func (m *Event_Body_Ad) GetTemplateId() uint32 {
	if m != nil && m.TemplateId != nil {
		return *m.TemplateId
	}
	return 0
}

type Event_Body_Charge struct {
	Type             *jesgoo_protocol1.ChargeType `protobuf:"varint,1,req,name=type,enum=jesgoo.protocol.ChargeType" json:"type,omitempty"`
	Price            *uint32                      `protobuf:"varint,2,req,name=price" json:"price,omitempty"`
	XXX_unrecognized []byte                       `json:"-"`
}

func (m *Event_Body_Charge) Reset()         { *m = Event_Body_Charge{} }
func (m *Event_Body_Charge) String() string { return proto.CompactTextString(m) }
func (*Event_Body_Charge) ProtoMessage()    {}

func (m *Event_Body_Charge) GetType() jesgoo_protocol1.ChargeType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return jesgoo_protocol1.ChargeType_FREE
}

func (m *Event_Body_Charge) GetPrice() uint32 {
	if m != nil && m.Price != nil {
		return *m.Price
	}
	return 0
}

type Event_Body_Action struct {
	TargetUrl        *string `protobuf:"bytes,1,opt,name=target_url" json:"target_url,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Event_Body_Action) Reset()         { *m = Event_Body_Action{} }
func (m *Event_Body_Action) String() string { return proto.CompactTextString(m) }
func (*Event_Body_Action) ProtoMessage()    {}

func (m *Event_Body_Action) GetTargetUrl() string {
	if m != nil && m.TargetUrl != nil {
		return *m.TargetUrl
	}
	return ""
}

func init() {
	proto.RegisterEnum("jesgoo.protocol.Event_Head_CryptoType", Event_Head_CryptoType_name, Event_Head_CryptoType_value)
	proto.RegisterEnum("jesgoo.protocol.Event_Body_EventType", Event_Body_EventType_name, Event_Body_EventType_value)
}
